// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaHeaven.Services;

namespace NinjaHeaven.Migrations
{
    [DbContext(typeof(NinjaHeavenDbContext))]
    partial class NinjaHeavenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NinjaHeaven.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(3380),
                            Description = "傷害+1",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/03/other_shuriken.png",
                            Name = "手裡劍",
                            Price = 5,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4050)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4670),
                            Description = "傷害+3",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/other_hammer_01.png",
                            Name = "鐵鎚",
                            Price = 10,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4670)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4670),
                            Description = "傷害+5",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/other_goldbar_01.png",
                            Name = "狼牙棒",
                            Price = 20,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4670)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4670),
                            Description = "傷害+50，速度+10",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/vehicle_tank_01.png",
                            Name = "戰車",
                            Price = 300,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4680)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4680),
                            Description = "速度+50",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/other_ufo_01.png",
                            Name = "UFO",
                            Price = 250,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4680)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4680),
                            Description = "體力+5",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/food_rice_03.png",
                            Name = "白飯",
                            Price = 10,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4680)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4680),
                            Description = "體力+10",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/other_babybottle_01.png",
                            Name = "牛奶",
                            Price = 20,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4680)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4680),
                            Description = "透視+5，魅力+5",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/other_glasses_01.png",
                            Name = "透視鏡",
                            Price = 50,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4690)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4690),
                            Description = "親密度+5",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/other_lettter_01.png",
                            Name = "信紙",
                            Price = 1,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4690)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4690),
                            Description = "全區喊話",
                            ImgUrl = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/other_trumpet_01.png",
                            Name = "大聲公",
                            Price = 10,
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 698, DateTimeKind.Utc).AddTicks(4690)
                        });
                });

            modelBuilder.Entity("NinjaHeaven.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Wallet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 691, DateTimeKind.Utc).AddTicks(4500),
                            Email = "kelly@gmail.com",
                            Gender = "Female",
                            Name = "Kelly",
                            Password = EncryptionService.Encrypt("123456"),
                            Role = "Admin",
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 691, DateTimeKind.Utc).AddTicks(5320),
                            Wallet = 1000
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 696, DateTimeKind.Utc).AddTicks(2950),
                            Email = "kevin@gmail.com",
                            Gender = "Male",
                            Name = "Kevin",
                            Password = EncryptionService.Encrypt("123456"),
                            Role = "Player",
                            UpdatedDate = new DateTime(2022, 4, 22, 11, 52, 47, 696, DateTimeKind.Utc).AddTicks(2950),
                            Wallet = 1000
                        });
                });

            modelBuilder.Entity("NinjaHeaven.Models.UserEquipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EquipmentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEquipment");
                });

            modelBuilder.Entity("NinjaHeaven.Models.UserEquipment", b =>
                {
                    b.HasOne("NinjaHeaven.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaHeaven.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
